diff --git a/Makefile b/Makefile
index bd5736f6..b5cf21e5 100644
--- a/Makefile
+++ b/Makefile
@@ -2,6 +2,7 @@
 ##  SETTINGS                                                                 ##
 ###############################################################################
 include project/settings.mk
+unexport AR
 
 # Modules
 COMMON := $(abspath modules/common)
