INSTALL_DIR="$HOME/.local"
mkdir -p "$INSTALL_DIR" && git clone https://github.com/Microsoft/vcpkg.git "$INSTALL_DIR/vcpkg" && bash "$INSTALL_DIR/vcpkg/bootstrap-vcpkg.sh"
echo "[TODO] Append following lines into your profile file: "
echo "export PATH=$INSTALL_DIR/vcpkg:\$PATH"
echo "export VCPKG_ROOT=$INSTALL_DIR/vcpkg"